baseURL: 'https://nicholasingerson.netlify.app/'
languageCode: en-us
title: Nicholas Ingerson
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: search
      name: Search
      url: /search
      weight: 50

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false
  authorImage: '/static/favicon.ico'

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: 'Nicholas Ingerson'
    subtitle: 'Digital Craftsman.'
    imageUrl: '/home/me.jpg'
    imageWidth: 220
    imageHeight: 220
    buttons:
    #  - name: Resume
    #    url: 'https://drive.google.com/file/d/1rwldxTY2vaW-1BGAza5GC5vej5UmdWj-NLrvtqesBOU/view'

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: 'email'
      url: 'mailto:nicholascingerson@gmail.com'
    - name: 'linkedin'
      url: 'https://www.linkedin.com/in/ningerson2002'
    - name: 'github'
      url: 'https://github.com/ningerson2002'
    - name: 'cv'
      url: 'https://drive.google.com/file/d/1rwldxTY2vaW-1BGAza5GC5vej5UmdWj-NLrvtqesBOU/view'

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title', 'permalink', 'summary', 'content']

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
